# action.yml
name: 'Build Docker Image'
on:
  workflow_dispatch:

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Checkout the merged commit from PR and base branch
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest

