name: 'Build Node with yarn'
on:
  workflow_dispatch:

jobs:
  client-build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout the merged commit from PR and base branch
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: client/package.json

      - name: run manual yarn install dependencies command
        run: yarn install --frozen-lockfile

      - name: build the bundle
        run: yarn build
      
