name: Test Cypress

on:
  workflow_dispatch:

jobs:
  ci-test:
    runs-on: self-hosted
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image for Redis
        image: redis
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v4

        
